sudo: true

install:
- UML_DOCKERCOMPOSE=0 UML_FIG=0 sh -xe .travis/uml-docker/install.sh

script:
- .travis/uml-docker/run "docker version && docker info"
- .travis/uml-docker/run docker run ubuntu /bin/echo hello world
